# Dockerfile para Laravel backend
FROM php:8.2-apache
WORKDIR /var/www/html
COPY backend-laravel/. .
RUN apt-get update && apt-get install -y libzip-dev unzip && docker-php-ext-install zip pdo pdo_mysql
